### ISSUE TITLE
User can login using github credentials

### ISSUE THREAD

**Issue by djay** [bkkhack/bkkhack.github.io#2]
Hit a snag with this issue. Their oauth doesnt support implicit grant which means we can't do oauth client side only. See http://stackoverflow.com/questions/18124633/authentication-on-github.

This leaves a couple of options

1. Small service on lambda or app engine to help with oauth. 
2. Switch to full app and store data in a db
3. Use basic authentication and get the user to login again.

**Comment by djay** [comment]
@bkkhack/hackmap what do you think?

**Comment by JeremyRms** [comment]
So, from my understanding, we need 2 things:

- [ ] User able to see current position of other people -> having access to Github issues where we store info
- [ ] We need to post an issue on behalf of this user

There's this reply to the problem :
```He asked specifically about basic auth, which you can definitely do from a browser. There's Octokit JS libraries that do it. – Carl Smith Aug 14 '14 at 16:59``` 
I think we can access issues, I am more sceptical on the ability to post for them.
I'll try to experiment with some app with postman what we can do with the API when you've got only a `personnal access token`.

**Comment by djay** [comment]
@JeremyZr I think the personal access token and the basic authentication are different things. I think the personal access token is not useful to us. Basic authentication would mean we ask the user for the username and password, store them in the browser and use them to make api calls. It will allow the same access as oauth2. The only difference is that the user has to trust us more since oauth would mean we never see their password + oauth means in many cases the user never enters their password or even hits a auth screen after the first time. So for convinience, oauth is by far preferable. 
But I think we can start with basic auth and see if the whole thing works, then setup up some small service to deal with oauth later.

**Comment by JeremyRms** [comment]
Fair enough, let's try that

**Comment by waf** [comment]
Resolved in https://github.com/bkkhack/hackmap/pull/2 using oauth.
