### ISSUE TITLE
changes to avatar are stored inside a github comment

### ISSUE THREAD

**Issue by djay** [bkkhack/bkkhack.github.io#3]
# Options

## In comments

Each change edits 1 IssueComment with e.g

```
Start to learn python
# X:238,Y:234
```

In this case a single github Issue represents 1 instance of an event. The background can be stored in the Issue description. The X,Y for a user can be stored relative to the image.

There is a notifications api that could be polled to get updates comments but I'm not sure it notifies on comment edits or not.

**Comment by waf** [comment]
Completed in https://github.com/bkkhack/hackmap/pull/2.
